name: run-currency-rate-check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1,4'
env:
  FIXER_API_KEY: ${{ secrets.FIXER_API_KEY }}
  IS_LOCAL: false
jobs:
  check-rate:
    name: Check currency rate EUR-JPY
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - run: go run .
