name: currency-rate-check-high-frequency

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1,3,5'
env:
  FIXER_API_KEY: ${{ secrets.FIXER_API_KEY }}
  SLACK_WEBHOOK_MONEY: ${{ secrets.SLACK_WEBHOOK_MONEY }}
  COINLAYER_API_ACCESS_KEY: ${{ secrets.COINLAYER_API_ACCESS_KEY }}
  IS_LOCAL: false
  DYNAMO_API: ${{ secrets.DYNAMO_API }}
  DYNAMO_SECRET: ${{ secrets.DYNAMO_SECRET }}
  DYNAMO_REGION: ${{ secrets.DYNAMO_REGION }}
jobs:
  check-rate-fiat:
    name: Check currency rate EUR, USD and JPY
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - run: go run . -type=fiat -frequency=high
  check-rate-crypto:
    name: Check currency rate crypto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - run: go run . -type=crypto -frequency=high
